name: Tournamentpvp
version: '1.0-SNAPSHOT'
main: org.dabhiru.tournamentpvp.Tournamentpvp
api-version: '1.21'
depend: [LuckPerms]
commands:
  link:
    usage: /link
    description:  link your discord id